(() => {
  const copyrightYear = document.querySelector('.copyright-year');
  if (copyrightYear) copyrightYear.textContent = new Date().getFullYear();
  const fontReady = document.fonts.load('800 30px "Coda Caption"');
  const context = document.createElement('canvas').getContext('2d');
  const namespace = 'http://www.w3.org/2000/svg';
  let sequence = 0;
  window.renderDesignHeading = (heading, label = heading.textContent) => fontReady.then(() => {
    const index = sequence++;
    const blue = heading.classList.contains('eyebrow') || heading.matches('.value-item h3');
    const orange = heading.matches('.section-title');
    const softBlue = heading.matches('.game-name, .value-item h3');
    const small = heading.matches('.value-item h3');
    const size = small ? 16 : heading.closest('footer') ? 27 : 30;
    context.font = `800 ${size}px "Coda Caption"`;
    const metrics = context.measureText(label);
    const width = Math.ceil(metrics.width + 12);
    const height = small ? 24 : 44;
    const svg = document.createElementNS(namespace, 'svg');
    svg.setAttribute('viewBox', `0 0 ${width} ${height}`);
    svg.setAttribute('class', 'design-heading');
    svg.style.width = `calc(${width} * var(--u))`;
    svg.style.maxWidth = '100%';
    svg.style.margin = 'auto';
    svg.setAttribute('aria-hidden', 'true');
    const fill = softBlue ? [['1%', '#67caff'], ['25%', '#effbff'], ['43%', '#b6e9ff'], ['100%', '#65c9fa']] : orange ? [['1%', '#ff9220'], ['25%', '#fff6bf'], ['43%', '#ffd579'], ['100%', '#ff7400']] : blue ? [['1%', '#20a4d8'], ['25%', '#bfdfff'], ['43%', '#79c3ff'], ['100%', '#0051ca']] : [['1%', '#20d83f'], ['25%', '#bfffce'], ['43%', '#baff79'], ['100%', '#00ca43']];
    const stroke = softBlue ? ['#3899c4', '#28799f'] : orange ? ['#da7808', '#833200'] : blue ? ['#0043fa', '#00126a'] : ['#1b9a52', '#005f02'];
    svg.innerHTML = `<defs><linearGradient id="fill${index}" x2="0" y2="1">${fill.map(([offset, color]) => `<stop offset="${offset}" stop-color="${color}"/>`).join('')}</linearGradient><linearGradient id="stroke${index}" x2="0" y2="1"><stop stop-color="${stroke[0]}"/><stop offset="1" stop-color="${stroke[1]}"/></linearGradient></defs>`;
    const text = document.createElementNS(namespace, 'text');
    text.setAttribute('x', String(width / 2));
    text.setAttribute('y', String((height + metrics.actualBoundingBoxAscent - metrics.actualBoundingBoxDescent) / 2));
    text.setAttribute('text-anchor', 'middle');
    text.setAttribute('fill', `url(#fill${index})`);
    text.setAttribute('stroke', `url(#stroke${index})`);
    text.setAttribute('stroke-width', '6');
    text.setAttribute('stroke-linejoin', 'round');
    text.setAttribute('paint-order', 'stroke fill');
    text.style.font = `800 ${size}px "Coda Caption"`;
    text.style.filter = softBlue ? 'none' : `drop-shadow(0px 2px 3px ${orange ? 'rgba(135, 56, 0, .39)' : blue ? 'rgba(0, 42, 95, .39)' : 'rgba(19, 115, 0, .39)'})`;
    text.textContent = label;
    svg.append(text);
    const accessibleText = document.createElement('span');
    accessibleText.className = 'visually-hidden';
    accessibleText.textContent = label;
    heading.replaceChildren(accessibleText, svg);
  });
  document.querySelectorAll('.section-title, .value-item h3, .site-footer p').forEach(heading => window.renderDesignHeading(heading));
})();
